### PR TITLE
Only load admin CSS when showing settings page

### PR DESCRIPTION
**Pull request by tommcc**
### All Submissions:

* [x] Have you followed the [plugin Contributing guideline](https://github.com/oidc-wp/openid-connect-generi/blob/dev/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

The `styles-admin.css` file currently loads even on the front-end pages of a site. Visitors should not be loading an extra request for admin-related styles, nor should unrelated admin pages.

This PR changes the enqueue of `styles-admin.css` to only happen when loading the settings page. While this CSS currently only affects the logging table, the naming suggests it could be used for any of the admin UI, which is only the settings page.

### How to test the changes in this Pull Request:

1. While logged out, load a page of your site.
2. Open the Network tab of your browser's developer tools.
3. You should not see `styles-admin.css` loading.
4. Now, log in and go to the OpenID settings page.
5. Looking back at the Network tab, you should now see `styles-admin.css` loading.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?

Note: I wasn't able to get the tests running properly to inspect/add tests, but hopefully this change should be both easy to review and easy to test manually, which may not require automated tests. If not, I can work on troubleshooting the docker-compose error I was getting in trying to run tests.

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

Only load admin CSS when showing settings page.

### CODE REVIEW

**Review by timnolte — APPROVED** [review]

**Comment by Avamander** [comment]
@timnolte could this be merged please?

**Comment by tommcc** [comment]
> @timnolte could this be merged please?

@daggerhart

**Comment by timnolte** [comment]
@tommcc no need to bump the PR, if you see there have already been a number of PRs merged within that last week. It looks like this PR was tagged for the 3.9 release but didn't make it into the Project for some reason.

**Comment by tommcc** [comment]
Apologies, I thought an additional approval was needed. Thanks for the update. 🙌

**Pull request merged**
