### PR TITLE
settings variables name hinting (helps IDE)

### PR DESCRIPTION
**Pull request by gassan**
### All Submissions:

* [ ] Have you followed the [plugin Contributing guideline](https://github.com/oidc-wp/openid-connect-generic/blob/dev/.github/CONTRIBUTING.md)?
It is a minor fix, so pulled for main vranch
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Added settings class property names to help IDE with hinting.

### CODE REVIEW

**Comment by gassan** [comment]
Please merge to the Sigleton pattern #190. It helps us with developing our plugins based on this one

**Comment by timnolte** [comment]
@gassan it appears that you didn't properly setup your local environment as the static analysis checks have failed, which should have run locally if you had fully setup the development environment as instructed in the Wiki.

Also, this needs to be created from, and merged with, the `dev` branch and not main.

I also question these additions since these are not properties of the settings page they are properties of the `OpenId_Connect_Generic_Option_Settings` class which already has these properties defined properly.

**Review by timnolte — CHANGES_REQUESTED** [review]
Proper contribution workflow needs to be followed. Static analysis fails and opened against the wrong branch.

**Comment by gassan** [comment]
LOL, this PR can be closed.

**Pull request closed without merging**
