### PR TITLE
Adding acr_values support

### PR DESCRIPTION
**Pull request by Glowsome**
### All Submissions:

* [X] Have you followed the [plugin Contributing guideline](https://github.com/oidc-wp/openid-connect-generi/blob/dev/.github/CONTRIBUTING.md)?
* [X] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR enhances the plugin with capabillities on handling acr_values - in which the request to the IDP includes a specific authentication contract as defined on the IDP.
Next to that enhancements have been made to also check - when set that the - if defined authentication contract is honored.

### How to test the changes in this Pull Request:

1. Define the added acr_values field option with a contract that exists on the IDP ie. urn:domain:contract:my_method_of_auth ( this is the exact name of the authentication uri as defined on a/the IDP.
2. Test login, and see that the added (acr_-)values to the url will influence the behaviour of the authentication contract with the IDP.
3. Verify manual url-manipulation check so it will error / disallow login ( remove the added acs_values from url manually and try it on your IDP)

### Other information:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [X] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

- Added acr_values support & verification checks that it when defined in options is honored.
-

### CODE REVIEW

**Review by timnolte — CHANGES_REQUESTED** [review]
@Glowsome there is a conflict on this and there are some coding standards items that appear to be off, I'm not quite clear on why all of the checks didn't run but I suspect it's due to this work having been created before the conversion to GitHub Actions. I would like to roll this into the next release, which I'd like to get out in the next week or so. Are you able to get your branch updated? Thanks!

**Comment by Glowsome** [comment]
> @Glowsome there is a conflict on this and there are some coding standards items that appear to be off, I'm not quite clear on why all of the checks didn't run but I suspect it's due to this work having been created before the conversion to GitHub Actions. I would like to roll this into the next release, which I'd like to get out in the next week or so. Are you able to get your branch updated? Thanks!

Hi @timnolte i have made changes after the first run failed, 
I will need to find some time to evaluate as to what is still off - dont know if i can facilitate that within the wanted timespan.

best regards, 

Glowsome

**Comment by timnolte** [comment]
@Glowsome hmm, I'm not quite clear on the effects of any of the recent code changes and how they would have any affect on working with your IDP. It seems like you are talking about the changes to the settings which expand the number of settings that can be set via environment variables, which shouldn't have any real impact if not used. I have merged quite a number of PRs at this point and I'm working through testing out the changes as well as implementing some fixes. No worries if you want to take some more time so we can work out getting the changes needed. I'll push this to the next release.

**Comment by Glowsome** [comment]
> @Glowsome hmm, I'm not quite clear on the effects of any of the recent code changes and how they would have any affect on working with your IDP. It seems like you are talking about the changes to the settings which expand the number of settings that can be set via environment variables, which shouldn't have any real impact if not used. I have merged quite a number of PRs at this point and I'm working through testing out the changes as well as implementing some fixes. No worries if you want to take some more time so we can work out getting the changes needed. I'll push this to the next release.

@timnolte : This might be me just being daft, but atm the conflict as stated by the checks from Github seems to revolve around one file.
As this contains alot of additional variables - without giving me insight as to where those are used i do not feel comfy in resolving the conflict as to the one file mentioned.
So either i am missing dependant files as to where all these new variables are being utilised, or github is just playing tricks with my mind :\

- Glowsome

**Comment by Glowsome** [comment]
@timnolte  i have resolved the conflict but i still see a failed test, but to see it i apparently need access granted to view it on your  snyk.

- Glowsome

**Comment by timnolte** [comment]
@Glowsome so there are a whole ton of commits in this PR that shouldn't be there. I'm not sure how you resolved your conflicts but really you should have rebased your branch with this main branch. This is another reason why you should be creating your work on a dedicated feature/fix branch and not be making the changes directly on the `dev` branch, even in your own fork. I'm not inclined to merge this PR in as there are too many commits in this branch that I am not comfortable with merging in without the risk of ending up causing major regression issues. I think it is going to be best to make sure you are starting with the latest `dev` branch and then supply a branch/PR that includes only your changes. I appreciate the time you had taken, and I apologize that this PR was left for so long while other work was done, but I just can't accept this PR in this state. If it's possible to at the very least break out your codes changes and just throw them into the comments in this PR and I can take it upon myself to get the changes prepared and merged in. I always hate doing this just because I like to make sure others get the credit through commit history for the work and contributions they make.

**Comment by Glowsome** [comment]
@timnolte i'll try to clean stuff up, but its gonna take a while :(

**Comment by timnolte** [comment]
Totally understand. No rush on my part.

**Comment by Glowsome** [comment]
@timnolte i have redone it all and only commited in a separate-feature branch so it doesnt get polluted ( mostly by my own faults) 
Going to close this PR and open a new one

**Pull request closed without merging**
